version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    links:
      - elasticsearch_exporter:elasticsearch_exporter
  elasticsearch_exporter:
    image: justwatch/elasticsearch_exporter:1.0.1
    command:
     - '-es.uri=http://localhost:9200'
     - '-es.all=true'
    restart: always
    ports:
      - 9108:9108
